export class ContactsFakeDb
{
    public static contacts = [
        {
            "id": "1",
            "name": "Haley",
            "lastName": "Adams",
            "avatar": "assets/images/avatars/Abbott.jpg",
            "bphone": "+1 (574) 267-0816",
            "jobTitle": "Distribution Center Specialist",
            "department": "Operations",
            "team": "Warehouse",
            "email": "hadams@orthopediatrics.com",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "2",
            "name": "Jillian",
            "lastName": "Albertson",
            "avatar": "assets/images/avatars/andrew.jpg",
            "bphone": "+1 (574) 267-0820",
            "jobTitle": "Distribution Center Specialist",
            "department": "Operations",
            "team": "Warehouse",
            "email": "jalbertson@orthopediatrics.com",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "3",
            "name": "Kriss",
            "lastName": "Anderson",
            "avatar": "assets/images/avatars/Shepard.jpg",
            "bphone": "+1 (574) 267-0897",
            "jobTitle": "VP of Quality Systems and Regulatory Affairs",
            "department": "Quality and Regulatory Affairs",
            "team": "Senior Management",
            "email": "kanderson@orthopediatrics.com",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "4",
            "name": "Peter",
            "lastName": "Armstrong",
            "avatar": "assets/images/avatars/carl.jpg",
            "bphone": "+1 (574) 267-0889",
            "jobTitle": "Chief Medical Officer",
            "department": "Medical Affairs",
            "team": "Executive",
            "email": "parmstrong@orthopediatrics.com",
            "phone": "+1 (574) 527-1042",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "5",
            "name": "Dave",
            "lastName": "Bailey",
            "avatar": "assets/images/avatars/Arnold.jpg",
            "bphone": "+1 (574) 267-0834",
            "jobTitle": "Executive Vice President",
            "department": "Operations",
            "team": "Exective",
            "email": "dbailey@orthopediatrics.com",
            "phone": "+1 (574) 514-8571",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "6",
            "name": "Luke",
            "lastName": "Baker",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 574 367 5321",
            "jobTitle": "Engineering Intern",
            "department": "Engineering",
            "team": "Trauma and Deformity Correction",
            "email": "lbaker@orthopediatrics.com",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "7",
            "name": "Danny",
            "lastName": "Ball",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0894",
            "jobTitle": "Orthex Sales Director",
            "department": "Sales Management",
            "team": "Orthex",
            "email": "dball@orthopediatrics.com",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "8",
            "name": "Joel",
            "lastName": "Batts",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0895",
            "jobTitle": "Senior Vice President of Science & Technoloy",
            "department": "Quality and Regulatory Affairs",
            "team": "Executive",
            "email": "jbatts@orthopediatrics.com",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "9",
            "name": "Rachel",
            "lastName": "Blossey",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0851",
            "jobTitle": "Managing Director for Scoliosis - West",
            "department": "Sales Management",
            "team": "Scoliosis",
            "email": "rblossey@orthopediatrics.com",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "10",
            "name": "Paula",
            "lastName": "Bowerman",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0888",
            "jobTitle": "Distribution Center Specialist",
            "department": "Operations",
            "team": "Warehouse",
            "email": "pbowerman@orthopediatrics.com",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "11",
            "name": "Karen",
            "lastName": "Brace",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0821",
            "jobTitle": "Office Manager",
            "department": "Management",
            "team": "Management",
            "email": "kbrace@orthopediatrics.com",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "12",
            "name": "Alec",
            "lastName": "Burchard",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0873",
            "jobTitle": "Quality Engineer",
            "department": "Quality and Regulatory Affairs",
            "team": "Quality",
            "email": "aburchard@orthopediatrics.com",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "13",
            "name": "Mike",
            "lastName": "Byrom",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0885",
            "jobTitle": "Regulatory Affairs Manager - International",
            "department": "Quality and Regulatory Affairs",
            "team": "International",
            "email": "mbyrom@orthopediatrics.com",
            "phone": "+1 (512) 470-5594",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "14",
            "name": "Juli",
            "lastName": "Caldwell",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0824",
            "jobTitle": "Warehouse & Planning Manager",
            "department": "Operations",
            "team": "Warehouse Management",
            "email": "jcaldwell@orthopediatrics.com",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "15",
            "name": "Katie",
            "lastName": "Caldwell",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0862",
            "jobTitle": "Loaner Program Manager",
            "department": "Operations",
            "team": "Loaners",
            "email": "kcaldwell@orthopediatrics.com",
            "phone": "+1 (574) 265-3369",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "16",
            "name": "Lori",
            "lastName": "Carpenter",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0852",
            "jobTitle": "Sales/Accounts Receivable Analyst",
            "department": "Finance",
            "team": "Sales and Accounts Receivable",
            "email": "lcarpenter@orthopediatrics.com",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "17",
            "name": "Sarah",
            "lastName": "Chapman",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0831",
            "jobTitle": "Accts Receivable Specialist",
            "department": "Finance",
            "team": "Accounts Receivable",
            "email": "schapman@orthopediatrics.com",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "18",
            "name": "Robin",
            "lastName": "Chauncey",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0866",
            "jobTitle": "Distribution Center Specialist",
            "department": "Operations",
            "team": "Warehouse",
            "email": "rchauncey@orthopediatrics.com",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "19",
            "name": "Joel",
            "lastName": "Christner",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0882",
            "jobTitle": "Design Engineer",
            "department": "Engineering",
            "team": "Trauma and Deformity Correction",
            "email": "jchristner@orthopediatrics.com",
            "phone": "+1 (616) 516-3677",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "20",
            "name": "Bruce",
            "lastName": "Cornell",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0827",
            "jobTitle": "Vice President of Operations",
            "department": "Operations",
            "team": "Senior Management",
            "email": "bcornell@orthopediatrics.com",
            "phone": "+1 (574) 268-8633",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "21",
            "name": "Jim",
            "lastName": "Crumley",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0847",
            "jobTitle": "Vice President of Quality Engineering",
            "department": "Quality and Regulatory Affairs",
            "team": "Senior Management",
            "email": "jcrumley@orthopediatrics.com",
            "phone": "+1 (574) 527-4258",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "22",
            "name": "David",
            "lastName": "Daniels",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0830",
            "jobTitle": "Vice President of Engineering - Scoliosis",
            "department": "Engineering",
            "team": "Scoliosis Senior Management",
            "email": "ddaniels@orthopediatrics.com",
            "phone": "+1 (574) 527-9162",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "23",
            "name": "Rick",
            "lastName": "Detlefsen",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0826",
            "jobTitle": "Senior Design Engineer",
            "department": "Engineering",
            "team": "Scoliosis",
            "email": "rdetlefsen@orthopediatrics.com",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "24",
            "name": "Courtney",
            "lastName": "Dillon",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0892",
            "jobTitle": "Distribution Center Specialist",
            "department": "Operations",
            "team": "Warehouse",
            "email": "cdillon@orthopediatrics.com",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "25",
            "name": "Phil",
            "lastName": "Dingman",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0845",
            "jobTitle": "Process Engineer",
            "department": "Operations",
            "team": "Process Engineering",
            "email": "pdingman@orthopediatrics.com",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "26",
            "name": "Jason",
            "lastName": "Dugger",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0868",
            "jobTitle": "Regulatory Affairs Specialist",
            "department": "Quality and Regulatory Affairs",
            "team": "Regulatory Affairs",
            "email": "jdugger@orthopediatrics.com",
            "phone": "+1 (574) 527-7741",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "27",
            "name": "Jay",
            "lastName": "Edington",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0818",
            "jobTitle": "Managing Director for Trauma and Deformity - West",
            "department": "Sales Management",
            "team": "Trauma and Deformity Correction",
            "email": "jedington@orthopediatrics.com",
            "phone": "+1 (805) 432-6705",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "28",
            "name": "TJ",
            "lastName": "Edwards",
            "avatar": "assets/images/avatars/profile.jpg",
            "jobTitle": "Sales Specialist",
            "department": "Sales",
            "team": "Scoliosis",
            "email": "tedwards@orthopediatrics.com",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "29",
            "name": "Cassie",
            "lastName": "Elkins",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0828",
            "jobTitle": "Customer Service Specialist",
            "department": "Operations",
            "team": "Customer Service",
            "email": "celkins@orthopediatrics.com",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "30",
            "name": "Douglas",
            "lastName": "Faria",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (119) 813-5923",
            "jobTitle": "Sales Manager – Brazil",
            "department": "Sales Management",
            "team": "International - Latin America",
            "email": "dfaria@orthopediatrics.com",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "31",
            "name": "Darren",
            "lastName": "Fugett",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0813",
            "jobTitle": "Packaging Engineering Project Manager",
            "department": "Operations",
            "team": "Packaging Engineering",
            "email": "dfugett@orthopediatrics.com",
            "phone": "+1 (574) 527-5081",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "32",
            "name": "Greg",
            "lastName": "Gaberino",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0896",
            "jobTitle": "Director of Supply Chain",
            "department": "Operations",
            "team": "Supply Chain Management",
            "email": "ggaberino@orthopediatrics.com",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "33",
            "name": "Veronica",
            "lastName": "Gawarecki",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0873",
            "jobTitle": "Scoliosis Engineering Intern",
            "department": "Engineering",
            "team": "Scoliosis",
            "email": "vgawarecki@orthopediatrics.com",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "34",
            "name": "Daniel",
            "lastName": "Gerritzen",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0842",
            "jobTitle": "General Counsel and VP of Legal",
            "department": "Legal",
            "team": "Executive",
            "email": "dgerritzen@orthopediatrics.com",
            "phone": "+1 (317) 874-8591",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "35",
            "name": "Collin",
            "lastName": "Gibbs",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0865",
            "jobTitle": "Research and Development Engineer",
            "department": "Engineering",
            "team": "Scoliosis",
            "email": "cgibbs@orthopediatrics.com",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "36",
            "name": "Grace",
            "lastName": "Gibbs",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0876",
            "jobTitle": "Engineering Project Manager",
            "department": "Engineering",
            "team": "Trauma and Deformity Correction",
            "email": "ggibbs@orthopediatrics.com",
            "phone": "+1 (303) 931-5955",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "37",
            "name": "Michael",
            "lastName": "Giordano",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0869",
            "jobTitle": "Engineering Project Manager",
            "department": "Engineering",
            "team": "Trauma and Deformity Correction",
            "email": "mgiordano@orthopediatrics.com",
            "phone": "+1 (219) 208-5112",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "38",
            "name": "Elissa",
            "lastName": "Goldner",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0871",
            "jobTitle": "Customer Service Specialist",
            "department": "Operations",
            "team": "Customer Service",
            "email": "egoldner@orthopediatrics.com",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "39",
            "name": "Aparicio",
            "lastName": "Goncalves",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0810",
            "jobTitle": "Senior Vice President of Sales - Latin America",
            "department": "Sales Management",
            "team": "International - Latin America",
            "email": "agoncalves@orthopediatrics.com",
            "phone": "+1 (801) 358-1605",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "40",
            "name": "Jennifer",
            "lastName": "Gregory",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0880",
            "jobTitle": "Regulatory Affairs Manager",
            "department": "Quality and Regulatory Affairs",
            "team": "Regulatory Affairs",
            "email": "jgregory@orthopediatrics.com",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "41",
            "name": "Jodi",
            "lastName": "Grindle",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0867",
            "jobTitle": "Loaner Processing Specialist",
            "department": "Operations",
            "team": "Warehouse and Loaners",
            "email": "jgrindle@orthopediatrics.com",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "42",
            "name": "Patrick",
            "lastName": "Groome",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0898",
            "jobTitle": "Engineering Project Manager",
            "department": "Engineering",
            "team": "Trauma and Deformity Correction",
            "email": "pgroome@orthopediatrics.com",
            "phone": "+1 (772) 538-3688",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "43",
            "name": "Collin",
            "lastName": "Grotbeck",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0837",
            "jobTitle": "Medical Education Program Manager",
            "department": "Education and Training",
            "team": "Education and Training",
            "email": "cgrotbeck@orthopediatrics.com",
            "phone": "+1 (574) 549-2402",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "44",
            "name": "Cristian",
            "lastName": "Gurrola",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0875",
            "jobTitle": "Design Engineer",
            "department": "Engineering",
            "team": "Trauma and Deformity Correction",
            "email": "cgurrola@orthopediatrics.com",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "45",
            "name": "Ryan",
            "lastName": "Harper",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0857",
            "jobTitle": "Research & Development Manager - Spine",
            "department": "Engineering",
            "team": "Scoliosis",
            "email": "rharper@orthopediatrics.com",
            "phone": "+1 (574) 265-5066",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "46",
            "name": "Randy",
            "lastName": "Harpster",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0890",
            "jobTitle": "Managing Director for Scoliosis - East",
            "department": "Sales Management",
            "team": "Scoliosis",
            "email": "rharpster@orthopediatrics.com",
            "phone": "+1 (216) 308-0119",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "47",
            "name": "Joe",
            "lastName": "Hauser",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0838",
            "jobTitle": "Vice President of Deformity Correction & Trauma",
            "department": "Trauma and Deformity Correction",
            "team": "Senior Management",
            "email": "jhauser@orthopediatrics.com",
            "phone": "+1 (260) 414-2558",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "48",
            "name": "Sarah",
            "lastName": "Heinrich",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0846",
            "jobTitle": "Customer Service Specialist",
            "department": "Operations",
            "team": "Customer Service",
            "email": "sheinrich@orthopediatrics.com",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "49",
            "name": "Fred",
            "lastName": "Hite",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0877",
            "jobTitle": "Chief Financial Officer",
            "department": "Finance",
            "team": "Executive",
            "email": "fhite@orthopediatrics.com",
            "phone": "+1 (260) 414-2696",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "50",
            "name": "Chester",
            "lastName": "Huang",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0812",
            "jobTitle": "Senior VP of Sales – Asia/Pacific",
            "department": "Sales Management",
            "team": "International - Asia Pacific",
            "email": "chuang@orthopediatrics.com",
            "phone": "+1 (781) 566-2688",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "51",
            "name": "Joe",
            "lastName": "Jaques",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0863",
            "jobTitle": "Sr. Managing Director for Scoliosis - Central",
            "department": "Sales Management",
            "team": "Scoliosis",
            "email": "jjaques@orthopediatrics.com",
            "phone": "+1 (574) 532-1331",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "52",
            "name": "Jackie",
            "lastName": "Jaskula",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0817",
            "jobTitle": "Regulatory Affairs Manager",
            "department": "Quality and Regulatory Affairs",
            "team": "Regulatory Affairs",
            "email": "jjaskula@orthopediatrics.com",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "53",
            "name": "Michelle",
            "lastName": "Jeffrey",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0850",
            "jobTitle": "VP of Financial Planning & Analysis",
            "department": "Finance",
            "team": "Senior Management",
            "email": "mjeffrey@orthopediatrics.com",
            "phone": "+1 (260) 416-2062",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "54",
            "name": "Leigh Anne",
            "lastName": "Jessop",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0872",
            "jobTitle": "Post Market Surveillance Coordinator",
            "department": "Quality and Regulatory Affairs",
            "team": "Quality",
            "email": "ljessop@orthopediatrics.com",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "55",
            "name": "Mark",
            "lastName": "Karshner",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0884",
            "jobTitle": "Senior Vice President of OUS Sales",
            "department": "Sales Management",
            "team": "International - Executive",
            "email": "mkarshner@orthopediatrics.com",
            "phone": "+1 (415) 710-1369",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "56",
            "name": "Troy",
            "lastName": "Kerwin",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0883",
            "jobTitle": "VP of Sales Operations",
            "department": "Sales Operations",
            "team": "Senior Management",
            "email": "tkerwin@orthopediatrics.com",
            "phone": "+1 (574) 315-6250",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "57",
            "name": "Richard",
            "lastName": "King",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+41 78 924 1003",
            "jobTitle": "VP of Sales - EMEA",
            "department": "Sales Management",
            "team": "International - EMEA",
            "email": "rking@orthopediatrics.com",
            "phone": "+41 78 781 55 84",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "58",
            "name": "Jane",
            "lastName": "Krider",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0859",
            "jobTitle": "Return Product Specialist",
            "department": "Operations",
            "team": "Warehouse",
            "email": "jkrider@orthopediatrics.com",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "59",
            "name": "Candi",
            "lastName": "Langmaid",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0855",
            "jobTitle": "Clinical Affairs Manager",
            "department": "Quality and Regulatory Affairs",
            "team": "Clinical Affairs",
            "email": "clangmaid@orthopediatrics.com",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "60",
            "name": "Victor",
            "lastName": "Lavi",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (412) 848-8358",
            "jobTitle": "Director of Product Management",
            "department": "Sales Management",
            "team": "Orthex and Senior Management",
            "email": "vlavi@orthopediatrics.com",
            "phone": "+1 (412) 848-8358",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "61",
            "name": "Rebecca",
            "lastName": "Lengyel",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0860",
            "jobTitle": "Engineering Project Manager",
            "department": "Engineering",
            "team": "Scoliosis",
            "email": "rlengyel@orthopediatrics.com",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "62",
            "name": "Yan",
            "lastName": "Li",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0864",
            "jobTitle": "Regulatory Affairs Associate Manager - International",
            "department": "Quality and Regulatory Affairs",
            "team": "Regulatory Affairs",
            "email": "yli@orthopediatrics.com",
            "phone": "+1 (919) 260-8346",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "63",
            "name": "Scott",
            "lastName": "Lubensky",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0874",
            "jobTitle": "Design Engineer",
            "department": "Engineering",
            "team": "Scoliosis",
            "email": "slubensky@orthopediatrics.com",
            "phone": "+1 (574) 904-1348",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "64",
            "name": "Cindy",
            "lastName": "Lursen",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0849",
            "jobTitle": "General Accounting Coordinator",
            "department": "Finance",
            "team": "Accounts Payable",
            "email": "clursen@orthopediatrics.com",
            "phone": "+1 (574) 253-2315",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "65",
            "name": "Alexandre",
            "lastName": "Mbaye",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "1+ (574) 221-8042",
            "jobTitle": "Graphic Designer",
            "department": "Marketing",
            "team": "Graphic Design",
            "email": "ambaye@orthopediatrics.com",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "66",
            "name": "Chad",
            "lastName": "McAlexander",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0839",
            "jobTitle": "Engineering Project Manager",
            "department": "Engineering",
            "team": "Scoliosis",
            "email": "cmcalexander@orthopediatrics.com",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "67",
            "name": "Ian",
            "lastName": "McClellan",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0881",
            "jobTitle": "Engineering Project Manager",
            "department": "Engineering",
            "team": "Trauma and Deformity Correction",
            "email": "imcclellan@orthopediatrics.com",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "68",
            "name": "Steve",
            "lastName": "McCormick",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0891",
            "jobTitle": "Director of Product Management",
            "department": "Marketing",
            "team": "Deformity Correction",
            "email": "smccormick@orthopediatrics.com",
            "phone": "+1 (574) 377-5845",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "69",
            "name": "Jeff",
            "lastName": "Mebel",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0819",
            "jobTitle": "Director of Product Management",
            "department": "Marketing",
            "team": "Trauma",
            "email": "jmebel@orthopediatrics.com",
            "phone": "+1 (901) 569-8986",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "70",
            "name": "Chris",
            "lastName": "Mefford",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0861",
            "jobTitle": "Director of Post Market Quality",
            "department": "Quality and Regulatory Affairs",
            "team": "Quality",
            "email": "cmefford@orthopediatrics.com",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "71",
            "name": "Tony",
            "lastName": "Metzinger",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "‪+1 (574) 268-2841",
            "jobTitle": "VP of Engineering",
            "department": "Engineering",
            "team": "Trauma and Deformity Correction Senior Management",
            "email": "tmetzinger@orthopediatrics.com",
            "phone": "+1 (574) 527-3185",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "72",
            "name": "Steve",
            "lastName": "Miller",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0853",
            "jobTitle": "VP of Finance",
            "department": "Finance",
            "team": "Senior Management",
            "email": "smiller@orthopediatrics.com",
            "phone": "+1 (574) 453-8468",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "73",
            "name": "Jeff",
            "lastName": "Minaudo",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0844",
            "jobTitle": "VP of Customer Service",
            "department": "Operations",
            "team": "Customer Service and Senior Management",
            "email": "jminaudo@orthopediatrics.com",
            "phone": "+1 (574) 527-8540",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "74",
            "name": "Paul",
            "lastName": "Mraz",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (781) 934-5441",
            "jobTitle": "Senior VP and GM of ApiFix",
            "department": "ApiFix",
            "team": "Executive",
            "email": "pmraz@orthopediatrics.com",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "75",
            "name": "Taylor",
            "lastName": "Mullahy",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0899",
            "jobTitle": "Engineering Project Manager",
            "department": "Engineering",
            "team": "Trauma and Deformity Correction",
            "email": "tmullahy@orthopediatrics.com",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "76",
            "name": "Archie",
            "lastName": "Newsome",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0811",
            "jobTitle": "Operations Process Manager",
            "department": "Operations",
            "team": "Process Engineering",
            "email": "anewsome@orthopediatrics.com",
            "phone": "+1 (574) 376-5187",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "77",
            "name": "Stacy",
            "lastName": "Newton",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0870",
            "jobTitle": "Field Inventory Analyst",
            "department": "Finance",
            "team": "Inventory Management",
            "email": "snewton@orthopediatrics.com",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "78",
            "name": "Matthew",
            "lastName": "Obrock",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0848",
            "jobTitle": "Engineering Project Manager",
            "department": "Engineering",
            "team": "Trauma and Deformity Correction",
            "email": "mobrock@orthopediatrics.com",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "79",
            "name": "Greg",
            "lastName": "Odle",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0835",
            "jobTitle": "Executive Vice President",
            "department": "Sales Management",
            "team": "Executive",
            "email": "godle@orthopediatrics.com",
            "phone": "+1 (317) 697-5031",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "80",
            "name": "Christian",
            "lastName": "Olney",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 574 267-0895",
            "jobTitle": "Warehouse Intern",
            "department": "Operations",
            "team": "Warehouse",
            "email": "colney@orthopediatrics.com",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "81",
            "name": "Sarah",
            "lastName": "Poorman",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0879",
            "jobTitle": "Engineering Project Manager",
            "department": "Engineering",
            "team": "Trauma and Deformity Correction",
            "email": "spoorman@orthopediatrics.com",
            "phone": "+1 (330) 635-0857",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "82",
            "name": "Chris",
            "lastName": "Powers",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0841",
            "jobTitle": "Design Engineer",
            "department": "Engineering",
            "team": "Trauma and Deformity Correction",
            "email": "cpowers@orthopediatrics.com",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "83",
            "name": "Mike",
            "lastName": "Pritchard",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0886",
            "jobTitle": "Sr. Managing Director for Trauma and Deformity - Central",
            "department": "Sales Management",
            "team": "Trauma and Deformity Correction",
            "email": "mpritchard@orthopediatrics.com",
            "phone": "+1 (317) 840-5470",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "84",
            "name": "Matt",
            "lastName": "Prygoski",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0832",
            "jobTitle": "Engineering Project Manager",
            "department": "Engineering",
            "team": "Scoliosis",
            "email": "mprygoski@orthopediatrics.com",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "85",
            "name": "Miranda",
            "lastName": "Roberson",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 221-8042",
            "jobTitle": "Scoliosis Engineering Intern",
            "department": "Engineering",
            "team": "Scoliosis",
            "email": "mroberson@orthopediatrics.com",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "86",
            "name": "Sandra",
            "lastName": "Rohrbach",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574)-267-0855",
            "jobTitle": "Warehouse Temp",
            "department": "Operations",
            "team": "Warehouse",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "87",
            "name": "Nancy",
            "lastName": "Sausaman",
            "avatar": "assets/images/avatars/profile.jpg",
            "jobTitle": "Quality Contractor",
            "department": "Quality and Regulatory Affairs",
            "team": "Quality",
            "email": "nsausaman@orthopediatrics.com",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "88",
            "name": "Mark",
            "lastName": "Serafino",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0887",
            "jobTitle": "Vice President of Sales Training & Education",
            "department": "Education and Training",
            "team": "Senior Management",
            "email": "mserafino@orthopediatrics.com",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "89",
            "name": "Brittani",
            "lastName": "Smith",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 268-2988",
            "jobTitle": "Regulatory Affairs Coordinator",
            "department": "Quality and Regulatory Affairs",
            "team": "Regulatory Affairs",
            "email": "bsmith@orthopediatrics.com",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "90",
            "name": "Jade",
            "lastName": "Smith",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0829",
            "jobTitle": "Paralegal",
            "department": "Legal",
            "team": "Paralegal",
            "email": "jsmith@orthopediatrics.com",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "91",
            "name": "Jeff",
            "lastName": "Smithey",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0856",
            "jobTitle": "VP of Spine",
            "department": "Scoliosis",
            "team": "Senior Management",
            "email": "jsmithey@orthopediatrics.com",
            "phone": "+1 (574) 527-8723",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "92",
            "name": "Jennifer",
            "lastName": "Sommers",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0814",
            "jobTitle": "Quality Engineer",
            "department": "Quality and Regulatory Affairs",
            "team": "Quality",
            "email": "jsommers@orthopediatrics.com",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "93",
            "name": "Darren",
            "lastName": "Stephens",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 268-2908",
            "jobTitle": "Managing Director – Northeast Region – T+D",
            "department": "Sales Management",
            "team": "Trauma and Deformity Correction",
            "email": "dstephens@orthopediatrics.com",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "94",
            "name": "Joe",
            "lastName": "Swisher",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0854",
            "jobTitle": "Applications Analyst",
            "department": "Information Technology",
            "team": "Applications",
            "email": "jswisher@orthopediatrics.com",
            "phone": "+1 (260) 242-0983",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "95",
            "name": "Greg",
            "lastName": "Teghtmeyer",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0840",
            "jobTitle": "Director of Logistics",
            "department": "Operations",
            "team": "Logistics",
            "email": "gteghtmeyer@orthopediatrics.com",
            "phone": "+1 (574) 529-5546",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "96",
            "name": "Dani",
            "lastName": "Thomas",
            "avatar": "assets/images/avatars/profile.jpg",
            "jobTitle": "Financial Planning & Analysis Manager",
            "department": "Finance",
            "team": "Financial Planning",
            "email": "dthomas@orthopediatrics.com",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "97",
            "name": "Mark",
            "lastName": "Throdahl",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0833",
            "jobTitle": "President & CEO",
            "department": "Executive",
            "team": "Executive",
            "email": "mthrodahl@orthopediatrics.com",
            "phone": "+1 (201) 961-5133",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "98",
            "name": "Evangelos",
            "lastName": "Tozakoglou",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0815",
            "jobTitle": "Managing Directory - EMEA",
            "department": "Sales and Operations",
            "team": "International - EMEA",
            "email": "etozako@orthopediatrics.com",
            "phone": "+1 (574) 527-5012",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "99",
            "name": "Shawn",
            "lastName": "Tribolet",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0822",
            "jobTitle": "Quality Engineer",
            "department": "Quality and Regulatory Affairs",
            "team": "Quality",
            "email": "stribolet@orthopediatrics.com",
            "phone": "+1 (574) 527-0706",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "100",
            "name": "Mallory",
            "lastName": "Trusty",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0825",
            "jobTitle": "VP of OP Experience",
            "department": "Human Resources",
            "team": "Human Resources and Marketing Communications",
            "email": "mtrusty@orthopediatrics.com",
            "phone": "+1 (260) 243-1098",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "101",
            "name": "Luis",
            "lastName": "Vega",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0878",
            "jobTitle": "Director of Research & Development Engineering",
            "department": "Engineering",
            "team": "Trauma and Deformity Correction",
            "email": "lvega@orthopediatrics.com",
            "phone": "+1 (717) 635-0063",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        },
        {
            "id": "102",
            "name": "Leslie",
            "lastName": "Wilson",
            "avatar": "assets/images/avatars/profile.jpg",
            "bphone": "+1 (574) 267-0843",
            "jobTitle": "Quality Systems Manager",
            "department": "Quality and Regulatory Affairs",
            "team": "Quality",
            "email": "lwilson@orthopediatrics.com",
            "address": "   ",
            "birthday": "       ",
            "notes": "     "
        }
        
      
        
    ];
    public static contactslist = [
        {
            'depid'      : '1',
            'desc'    : 'Sales',         
        },
        {
            'depid'      : '2',
            'desc'    : 'Engineering',     
        },
        {
            'depid'      : '3',
            'desc'    : 'Quality and Regulatory Affairs',        
        },
        {
            'depid'      : '4',
            'desc'    : 'Finance',        
        }
    ];

    public static user = [
        {
            'id'              : '5725a6802d10e277a0f35724',
            'name'            : 'John Doe',
            'avatar'          : 'assets/images/avatars/profile.jpg',
            'starred'         : [
                '5725a680ae1ae9a3c960d487',
                '5725a6801146cce777df2a08',
                '5725a680bbcec3cc32a8488a',
                '5725a680bc670af746c435e2',
                '5725a68009e20d0a9e9acf2a'
            ],
            'frequentContacts': [
                '5725a6809fdd915739187ed5',
                '5725a68031fdbb1db2c1af47',
                '5725a680606588342058356d',
                '5725a680e7eb988a58ddf303',
                '5725a6806acf030f9341e925',
                '5725a68034cb3968e1f79eac',
                '5725a6801146cce777df2a08',
                '5725a680653c265f5c79b5a9'
            ],
            'groups'          : [
                {
                    'id'        : '5725a6802d10e277a0f35739',
                    'name'      : 'Friends',
                    'contactIds': [
                        '5725a680bbcec3cc32a8488a',
                        '5725a680e87cb319bd9bd673',
                        '5725a6802d10e277a0f35775'
                    ]
                },
                {
                    'id'        : '5725a6802d10e277a0f35749',
                    'name'      : 'Clients',
                    'contactIds': [
                        '5725a680cd7efa56a45aea5d',
                        '5725a68018c663044be49cbf',
                        '5725a6809413bf8a0a5272b1',
                        '5725a6803d87f1b77e17b62b'
                    ]
                },
                {
                    'id'        : '5725a6802d10e277a0f35329',
                    'name'      : 'Recent Workers',
                    'contactIds': [
                        '5725a680bbcec3cc32a8488a',
                        '5725a680653c265f5c79b5a9',
                        '5725a6808a178bfd034d6ecf',
                        '5725a6801146cce777df2a08'
                    ]
                }
            ]
        }
    ];
}
