export class DistributorsFakeDb
{
    public static distributors = [
        {
            "id": "1",
            "name": " David ",
            "lastName": "Steinberg",
            "avatar": "assets/images/avatars/dist-core.jpg",
            "region": "East",
            "city": "Miami",
            "email": " david.steinberg@coremedfl.com ",
            "phone": "941-525-6860",
            "address": "Miami, Fort Lauderdale, Tampa, Orlando",
            "cname": "CORE",
            "state": "Orlando",
            "zcode": "  "
        },
        {
            "id": "2",
            "name": " Jessi ",
            "lastName": "Asmundson",
            "avatar": "assets/images/avatars/dist-logo.jpg",
            "region": "East",
            "city": "Georgia",
            "email": " Jessi.prahl@outlook.com ",
            "phone": "404-406-9446",
            "address": "Georgia",
            "cname": "EAV",
            "state": "Georgia",
            "zcode": "  "
        },
        {
            "id": "3",
            "name": " Joel ",
            "lastName": "Huebner",
            "avatar": "assets/images/avatars/dist-logo.jpg",
            "region": "East",
            "city": "Jacksonville",
            "email": " joelhuebner@comcast.net ",
            "phone": "904-535-4421",
            "address": "Jacksonville, Gainesville, Savannah, GA",
            "cname": "Imagine",
            "state": "GA",
            "zcode": "  "
        },
        {
            "id": "4",
            "name": " David ",
            "lastName": "Inge",
            "avatar": "assets/images/avatars/dist-logo.jpg",
            "region": "East",
            "email": " dginge@hotmail.com ",
            "phone": "251-463-6662",
            "address": "Mobile,AL and Florida Panhandle",
            "cname": "Inge",
            "state": "Florida",
            "zcode": "  "
        },
        {
            "id": "5",
            "name": " Sam ",
            "lastName": "Salhab",
            "avatar": "assets/images/avatars/dist-logo.jpg",
            "region": "East",
            "city": "Viginia Beach",
            "email": " samsalhab@gmail.com ",
            "phone": "804-399-3327",
            "address": "Virgina Beach, Richmond, VA",
            "cname": "KNS",
            "state": "VA",
            "zcode": "  "
        },
        {
            "id": "6",
            "name": " Zach ",
            "lastName": "Cleary",
            "avatar": "assets/images/avatars/dist-logo.jpg",
            "region": "East",
            "email": " zcleary@gmail.com ",
            "phone": "(980) 833-3660",
            "address": "North Carolina, South Carolina Dayton, Toledo, Columbus",
            "cname": "NuSpine",
            "state": "North Carolina",
            "zcode": "  "
        },
        {
            "id": "7",
            "name": " Mike ",
            "lastName": "Lillie",
            "avatar": "assets/images/avatars/dist-logo.jpg",
            "region": "East",
            "email": " mlillie@bellsouth.net ",
            "phone": "205-965-0835",
            "address": "Birmingham, AL",
            "cname": "Titan",
            "state": "Birmingham",
            "zcode": "  "
        },
        {
            "id": "8",
            "name": " Kevin ",
            "lastName": "Graham",
            "avatar": "assets/images/avatars/dist-logo.jpg",
            "region": "East",
            "city": "Cleveland",
            "email": " kevingraham@roadrunner.com ",
            "phone": "216-570-1057",
            "address": "Cleveland, Akron, Pittsburgh, Morgantown",
            "cname": "Ohio Fusion",
            "state": "Pittsburgh",
            "zcode": "  "
        },
        {
            "id": "9",
            "name": " Jeff ",
            "lastName": "Golden",
            "avatar": "assets/images/avatars/dist-logo.jpg",
            "region": "East",
            "city": "Palm Beach",
            "email": " jgolden@ortho-max.net ",
            "phone": "772-201-0852",
            "address": "Palm Beach, FL",
            "cname": "OrthoMax",
            "state": "Florida",
            "zcode": "  "
        },
        {
            "id": "10",
            "name": " Ilya ",
            "lastName": "Nudelman",
            "avatar": "assets/images/avatars/dist-logo.jpg",
            "region": "East",
            "email": " ilya.nudelman01@gmail.com ",
            "phone": "410-456-6478",
            "address": "Baltimore, Washington DC",
            "cname": "OsteoSolutions",
            "state": "Washington",
            "zcode": "  "
        },
        {
            "id": "11",
            "name": " Tim ",
            "lastName": "Hinspeter",
            "avatar": "assets/images/avatars/dist-logo.jpg",
            "region": "East",
            "email": " thinspeter@orthopediatrics.com ",
            "phone": "845-742-7005",
            "address": "NY, CT, RI, MA, NJ, Eastern PA, DE",
            "cname": "Trauma Recon",
            "zcode": "  "
        },
        {
            "id": "12",
            "name": " Todd ",
            "lastName": "Lichty",
            "avatar": "assets/images/avatars/dist-logo.jpg",
            "region": "Central",
            "city": "Rochester",
            "email": " tlichty@alignsurgicalsupplyllc.com ",
            "phone": "507- 993-6247",
            "address": "Rochester, MN, North Dakota, South Dakota",
            "cname": "Align",
            "zcode": "  "
        },
        {
            "id": "13",
            "name": " Allan ",
            "lastName": "Garvin",
            "avatar": "assets/images/avatars/dist-logo.jpg",
            "region": "Central",
            "email": " agarvin@alliantsurg.com ",
            "phone": "317-696-2847",
            "address": "Indiana, except South Bend",
            "cname": "Alliant",
            "state": "Indiana",
            "zcode": "  "
        },
        {
            "id": "14",
            "name": " Mary Kate ",
            "lastName": "Rosenfelder",
            "avatar": "assets/images/avatars/dist-logo.jpg",
            "region": "Central",
            "email": " mrosenfelder@orthopediatrics.com ",
            "phone": "630-877-1015",
            "address": "Chicago",
            "cname": "RoseMed",
            "state": "Chicago",
            "zcode": "  "
        },
        {
            "id": "15",
            "name": " TJ ",
            "lastName": "Edwards",
            "avatar": "assets/images/avatars/dist-logo.jpg",
            "region": "Central",
            "email": " tedwards@orthopediatrics.com ",
            "phone": "219-771-3163",
            "address": "Chicago",
            "cname": "TJ Edwards",
            "state": "Chicago",
            "zcode": "  "
        },
        {
            "id": "16",
            "name": " Jeff ",
            "lastName": "Ettinger",
            "avatar": "assets/images/avatars/dist-logo.jpg",
            "region": "Central",
            "email": " 28bonesmedical@gmail.com ",
            "phone": "(847) 809-5103",
            "address": "Chicago",
            "cname": "28 Bones Medical",
            "state": "Chicago",
            "zcode": "  "
        },
        {
            "id": "17",
            "name": " Jacob ",
            "lastName": "Rowe",
            "avatar": "assets/images/avatars/dist-logo.jpg",
            "region": "Central",
            "city": "Kansas",
            "email": " jacobtrowe@gmail.com ",
            "phone": "573-673-7305",
            "address": "Missouri, Iowa, Nebraska, Kansas",
            "cname": "JTR",
            "state": "Missouri",
            "zcode": "  "
        },
        {
            "id": "18",
            "name": " Perry ",
            "lastName": "Moss",
            "avatar": "assets/images/avatars/dist-logo.jpg",
            "region": "Central",
            "email": " perry@m3med.net ",
            "phone": "318-525-8878",
            "address": "Central Louisana",
            "cname": "M3 Medical",
            "state": "Lousiana",
            "zcode": "  "
        },
        {
            "id": "19",
            "name": " Melanie ",
            "lastName": "Arnold",
            "avatar": "assets/images/avatars/dist-logo.jpg",
            "region": "Central",
            "city": "Kentucky",
            "email": " marnold@orthopediatrics.com ",
            "phone": "502-558-6565",
            "address": "Kentucky, Huntington,WV, Cincinnatti",
            "cname": "MK Medical",
            "state": "cincinatti",
            "zcode": "  "
        },
        {
            "id": "20",
            "name": " Matt ",
            "lastName": "Milanowski",
            "avatar": "assets/images/avatars/dist-logo.jpg",
            "region": "Central",
            "email": " milanowskimatt@gmail.com ",
            "phone": "616-304-4668",
            "address": "Michigan",
            "cname": "MKS Ventures",
            "state": "Michigan",
            "zcode": "  "
        },
        {
            "id": "21",
            "name": " Mark ",
            "lastName": "Slaughter",
            "avatar": "assets/images/avatars/dist-logo.jpg",
            "region": "Central",
            "email": " mslaughter@onbelaymedical.com ",
            "phone": "865- 387-0350",
            "address": "Nashville, Chatt, Knoxville",
            "cname": "On-Belay ",
            "state": "Nashville",
            "zcode": "  "
        },
        {
            "id": "22",
            "name": " Mark ",
            "lastName": "Phillips",
            "avatar": "assets/images/avatars/dist-logo.jpg",
            "region": "Central",
            "email": " mphillips@orthopediatrics.com ",
            "phone": "214-497-2533",
            "address": "Texas, Louisana, Mississippi, Tulsa, Arkansas",
            "cname": "PeDS",
            "state": "Texas",
            "zcode": "  "
        },
        {
            "id": "23",
            "name": " Nick ",
            "lastName": "Schweitzer",
            "avatar": "assets/images/avatars/dist-logo.jpg",
            "region": "Central",
            "email": " nschwtzr@gmail.com ",
            "phone": "901-237-4147",
            "address": "Memphis",
            "cname": "Quality Control",
            "state": "Memphis",
            "zcode": "  "
        },
        {
            "id": "24",
            "name": " Greg ",
            "lastName": "Oplotnik",
            "avatar": "assets/images/avatars/dist-logo.jpg",
            "region": "Central",
            "email": " goplotnik@rxmedicalokc.com ",
            "phone": "405- 417-6743",
            "address": "Oklahoma City",
            "cname": "RX Medical",
            "state": "Oklahoma City",
            "zcode": "  "
        },
        {
            "id": "25",
            "name": " Mike ",
            "lastName": "Flynn",
            "avatar": "assets/images/avatars/dist-logo.jpg",
            "region": "West",
            "email": " Aidinortho@gmail.com ",
            "phone": "720-435-8840",
            "address": "Colorado",
            "cname": "Aidin Ortho",
            "state": "Colorado",
            "zcode": "  "
        },
        {
            "id": "26",
            "name": " Bob ",
            "lastName": "Peirce",
            "avatar": "assets/images/avatars/dist-logo.jpg",
            "region": "West",
            "email": " rwp3@cox.net ",
            "phone": "602-330-2663",
            "address": "Phoenix, Tucson",
            "cname": "Arcadia",
            "state": "Tucson",
            "zcode": "  "
        },
        {
            "id": "27",
            "name": " Jeff ",
            "lastName": "Scaggs",
            "avatar": "assets/images/avatars/dist-logo.jpg",
            "region": "West",
            "email": " scaggsbones@gmail.com ",
            "phone": "208-602-8338",
            "address": "Boise, ID",
            "cname": "Bone & Joint",
            "zcode": "  "
        },
        {
            "id": "28",
            "name": " Jerry ",
            "lastName": "Miller",
            "avatar": "assets/images/avatars/dist-logo.jpg",
            "region": "West",
            "email": " jmiller@orthopediatrics.com ",
            "phone": "330-416-1836",
            "address": "Hawaii",
            "cname": "CCK Medical",
            "state": "Hawaai",
            "zcode": "  "
        },
        {
            "id": "29",
            "name": " Dave ",
            "lastName": "Hawkes",
            "avatar": "assets/images/avatars/dist-logo.jpg",
            "region": "West",
            "email": " hawkesda@outlook.com ",
            "phone": "312-841-1234",
            "address": "Utah",
            "cname": "Cub Med LLC",
            "state": "Utah",
            "zcode": "  "
        },
        {
            "id": "30",
            "name": " Marty ",
            "lastName": "Holbus",
            "avatar": "assets/images/avatars/dist-logo.jpg",
            "region": "West",
            "email": " mholbus@hhmed.com ",
            "phone": "916-240-1767",
            "address": "Sacramento",
            "cname": "H&H Medical",
            "state": "Sacrament",
            "zcode": "  "
        },
        {
            "id": "31",
            "name": " Rick ",
            "lastName": "Maly",
            "avatar": "assets/images/avatars/dist-logo.jpg",
            "region": "West",
            "email": " ricksmaly@outlook.com ",
            "phone": "760-685-5155  ",
            "address": "SanDiego, LAX, Fresno",
            "cname": "Medical Innovations",
            "state": "SanDiego",
            "zcode": "  "
        },
        {
            "id": "32",
            "name": " Brad ",
            "lastName": "Veach",
            "avatar": "assets/images/avatars/dist-logo.jpg",
            "region": "West",
            "email": " Brad.veach@norcalortho.org ",
            "phone": "925-997-4599 ",
            "address": "SanFran, Sacramento",
            "cname": "NorCal",
            "state": "Sacramento",
            "zcode": "  "
        },
        {
            "id": "33",
            "name": " Toby ",
            "lastName": "Cernik",
            "avatar": "assets/images/avatars/dist-logo.jpg",
            "region": "West",
            "email": " toby@NWbiosupply.com ",
            "phone": "406-214-1667",
            "address": "Montana",
            "cname": "NW BioSupply",
            "state": "Montana",
            "zcode": "  "
        },
        {
            "id": "34",
            "name": "Eddy",
            "lastName": "Kraus",
            "avatar": "assets/images/avatars/dist-logo.jpg",
            "region": "West",
            "email": "ekraus87@gmail.com",
            "phone": "503-997-1166",
            "address": "Portland, OR",
            "cname": "OJI",
            "state": "Portland",
            "zcode": "  "
        },
        {
            "id": "35",
            "name": "Joe",
            "lastName": "Jones",
            "avatar": "assets/images/avatars/dist-logo.jpg",
            "region": "West",
            "email": "joej@omegasurg.com",
            "phone": "425-503-9242",
            "address": "Washington",
            "cname": "Omega",
            "state": "Washington",
            "zcode": "  "
        },
        {
            "id": "36",
            "name": "Mike",
            "lastName": "McDonald",
            "avatar": "assets/images/avatars/dist-logo.jpg",
            "region": "West",
            "email": "mcdbones@cox.net",
            "phone": "702-501-7952",
            "address": "LasVegas",
            "cname": "Ortho Source",
            "state": "LasVegas",
            "zcode": "  "
        },
        {
            "id": "37",
            "name": "Quincy",
            "lastName": "Gonzales",
            "avatar": "assets/images/avatars/dist-logo.jpg",
            "region": "West",
            "email": "qgonzales@wesellortho.com",
            "phone": "505-888-1423",
            "address": "New Mexico",
            "cname": "Summit Medical",
            "state": "New Mexico",
            "zcode": "  "
        },
        {
            "id": "38",
            "name": "Samantha",
            "lastName": "Santos",
            "avatar": "assets/images/avatars/dist-logo.jpg",
            "region": "West",
            "email": "samiss@me.com",
            "phone": "801-874-9442",
            "address": "Salt Lake City, UT",
            "cname": "SCS",
            "state": "UT",
            "zcode": "  "
        },
       
        
    ];

    public static user = [
        {
            'id'              : '5725a6802d10e277a0f35724',
            'name'            : 'John Doe',
            'avatar'          : 'assets/images/avatars/dist-logo.jpg',
            'starred'         : [
                '5725a680ae1ae9a3c960d487',
                '5725a6801146cce777df2a08',
                '5725a680bbcec3cc32a8488a',
                '5725a680bc670af746c435e2',
                '5725a68009e20d0a9e9acf2a'
            ],
            'frequentDistributors': [
                '5725a6809fdd915739187ed5',
                '5725a68031fdbb1db2c1af47',
                '5725a680606588342058356d',
                '5725a680e7eb988a58ddf303',
                '5725a6806acf030f9341e925',
                '5725a68034cb3968e1f79eac',
                '5725a6801146cce777df2a08',
                '5725a680653c265f5c79b5a9'
            ],
            'groups'          : [
                {
                    'id'        : '5725a6802d10e277a0f35739',
                    'name'      : 'Friends',
                    'distributorIds': [
                        '5725a680bbcec3cc32a8488a',
                        '5725a680e87cb319bd9bd673',
                        '5725a6802d10e277a0f35775'
                    ]
                },
                {
                    'id'        : '5725a6802d10e277a0f35749',
                    'name'      : 'Clients',
                    'distributorIds': [
                        '5725a680cd7efa56a45aea5d',
                        '5725a68018c663044be49cbf',
                        '5725a6809413bf8a0a5272b1',
                        '5725a6803d87f1b77e17b62b'
                    ]
                },
                {
                    'id'        : '5725a6802d10e277a0f35329',
                    'name'      : 'Recent Workers',
                    'distributorIds': [
                        '5725a680bbcec3cc32a8488a',
                        '5725a680653c265f5c79b5a9',
                        '5725a6808a178bfd034d6ecf',
                        '5725a6801146cce777df2a08'
                    ]
                }
            ]
        }
    ];
}
